### ISSUE TITLE
Does authomatic.verify return a promise?

### ISSUE THREAD

**Issue by dicearr** [wearereasonablepeople/authomatic#30]
AFAIK, [`jsonwebtoken.verify`](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) is asynchronous only if a callback is provided.
No callback is given in authomatic:

```js
  const verify = (token, secret, verifyOptions = {}) =>
    jwt.verify(Token(token), Secret(secret), {
      ...defaultVerifyOptions,
      ...VerifyOptions(verifyOptions),
      algorithm: algorithm
    });
```

But according to the [docs](https://github.com/wearereasonablepeople/authomatic/blob/a15e852a383ef39ce529841bed87c1592bcc43f2/index.js#L240) `authomatic.verify` is returning a promise.

**Comment by Amri91** [comment]
Nope, I'll update the docs momentarily. Thanks!
